# Generated by Django 5.0.7 on 2024-08-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'web_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='products/images/')),
                ('featured_image', models.ImageField(blank=True, upload_to='products/images/')),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('stock', models.IntegerField()),
                ('category', models.ManyToManyField(related_name='products', to='web.category')),
            ],
            options={
                'db_table': 'web_product',
            },
        ),
    ]
